# Generated by Django 5.2.2 on 2025-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('diseaseNID', models.IntegerField(primary_key=True, serialize=False)),
                ('diseaseId', models.CharField(max_length=20)),
                ('diseaseName', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diseaseAttributes',
            },
        ),
        migrations.CreateModel(
            name='Disease2Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseNID', models.IntegerField()),
                ('diseaseClassNID', models.IntegerField()),
            ],
            options={
                'db_table': 'disease2class',
            },
        ),
        migrations.CreateModel(
            name='DiseaseClass',
            fields=[
                ('diseaseClassNID', models.IntegerField(primary_key=True, serialize=False)),
                ('vocabulary', models.CharField(max_length=50)),
                ('diseaseClass', models.CharField(max_length=10)),
                ('diseaseClassName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diseaseClass',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('geneNID', models.IntegerField(primary_key=True, serialize=False)),
                ('geneId', models.CharField(max_length=20)),
                ('geneName', models.CharField(max_length=255)),
                ('geneDescription', models.TextField(null=True)),
                ('pLI', models.FloatField(null=True)),
                ('DSI', models.FloatField(null=True)),
                ('DPI', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'geneAttributes',
            },
        ),
        migrations.CreateModel(
            name='VariantDisease',
            fields=[
                ('NID', models.IntegerField(primary_key=True, serialize=False)),
                ('diseaseNID', models.IntegerField()),
                ('variantNID', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'variantDiseaseNetwork',
            },
        ),
    ]
